version: '3.9'
services: 
  app: 
    build: 
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./webapp:/app
    depends_on:
      - db
    

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=mlops
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=8888

  pg:
    image: dpage/pgadmin4
    environment:
      -PGADMIN_DEFAULT_EMAIL: admin@admin.com
      -PGADMIN_DEFAULT_PASSWORD: 8888  
    ports:
      - "5050:80"