base:
  project: mlops_project
  random_state: 20
  target_col: charges

data_source:
  raw_dataset_csv: data/raw/insurance.csv

load_data:
  cleaned_data: data/processed/insurance_pr.csv

split_data:
  train_path: data/processed/train_data.csv
  test_path: data/processed/test_data.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      alpha: 0.9
      l1_ratio: 0.7

model_path: models/models.joblib

# reports:
#   params: reports/params.json
#   score: reports/scores.json

mlflow_config:
  artifacts_dir: artifacts 
  experiment_name: insurance_experiment
  run_name: insurance_run
  registered_model_name: insurance_model
  remote_server_uri: http://127.0.0.1:5000