name: Build, Analyze, Scan

on:
  push:
    branches:
      - main

jobs:
  build_analyze_scan:
    name: Build
    runs-on: ubuntu-latest        #[self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo usermod -aG docker $USER
          newgrp docker
          docker --version
          docker-compose --version  # Verify installation

      - name: Docker Build and Push
        env:
          DOCKER_CLI_ACI: 1
        run: |
          docker-compose -f docker-compose.yaml build
          docker tag webapp:latest frosty888/webapp:latest
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push frosty888/webapp:latest
