name: Build, Analyze, Scan

on:
  push:
    branches:
      - main

jobs:
  build_analyze_scan:
    name: Build
    runs-on: ubuntu-latest        #[self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt  # Fixed indentation

      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose
          docker-compose version  # Verify installation

      - name: Docker Build and Push
        env:
          DOCKER_CLI_ACI: 1
        run: |
          docker-compose -f docker-compose.yaml build
          docker tag webapp:latest frosty888/webapp:latest
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push frosty888/webapp:latest
